//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class coreModule
    {
        public coreModule()
        {
            this.coreOperation = new HashSet<coreOperation>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid SubsystemId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string UiId { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual ICollection<coreOperation> coreOperation { get; set; }
        public virtual coreSubsystem coreSubsystem { get; set; }
    }
}
