//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class coreFiscalYear
    {
        public coreFiscalYear()
        {
            this.corePeriod = new HashSet<corePeriod>();
            this.PRProductionOrderHeader = new HashSet<PRProductionOrderHeader>();
            this.psmsBinCard = new HashSet<psmsBinCard>();
            this.psmsDeliveryOrderHeader = new HashSet<psmsDeliveryOrderHeader>();
            this.psmsDisposalHeader = new HashSet<psmsDisposalHeader>();
            this.psmsInventoryRecord = new HashSet<psmsInventoryRecord>();
            this.psmsPurchaseOrderHeader = new HashSet<psmsPurchaseOrderHeader>();
            this.psmsPurchaseRequestHeader = new HashSet<psmsPurchaseRequestHeader>();
            this.psmsReturnHeader = new HashSet<psmsReturnHeader>();
            this.psmsTransferIssueHeader = new HashSet<psmsTransferIssueHeader>();
            this.psmsTransferReceiveHeader = new HashSet<psmsTransferReceiveHeader>();
            this.slmsProformaHeader = new HashSet<slmsProformaHeader>();
            this.psmsIssueHeader = new HashSet<psmsIssueHeader>();
            this.psmsReceiveHeader = new HashSet<psmsReceiveHeader>();
            this.psmsStoreRequisitionHeader = new HashSet<psmsStoreRequisitionHeader>();
            this.psmsAdjustmentHeader = new HashSet<psmsAdjustmentHeader>();
            this.psmsDelivery = new HashSet<psmsDelivery>();
            this.psmsFreightOrder = new HashSet<psmsFreightOrder>();
            this.psmsTransportation = new HashSet<psmsTransportation>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> NumberOfPeriods { get; set; }
        public bool IsActive { get; set; }
        public bool IsPreviousActive { get; set; }
        public bool IsClosed { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual ICollection<corePeriod> corePeriod { get; set; }
        public virtual ICollection<PRProductionOrderHeader> PRProductionOrderHeader { get; set; }
        public virtual ICollection<psmsBinCard> psmsBinCard { get; set; }
        public virtual ICollection<psmsDeliveryOrderHeader> psmsDeliveryOrderHeader { get; set; }
        public virtual ICollection<psmsDisposalHeader> psmsDisposalHeader { get; set; }
        public virtual ICollection<psmsInventoryRecord> psmsInventoryRecord { get; set; }
        public virtual ICollection<psmsPurchaseOrderHeader> psmsPurchaseOrderHeader { get; set; }
        public virtual ICollection<psmsPurchaseRequestHeader> psmsPurchaseRequestHeader { get; set; }
        public virtual ICollection<psmsReturnHeader> psmsReturnHeader { get; set; }
        public virtual ICollection<psmsTransferIssueHeader> psmsTransferIssueHeader { get; set; }
        public virtual ICollection<psmsTransferReceiveHeader> psmsTransferReceiveHeader { get; set; }
        public virtual ICollection<slmsProformaHeader> slmsProformaHeader { get; set; }
        public virtual ICollection<psmsIssueHeader> psmsIssueHeader { get; set; }
        public virtual ICollection<psmsReceiveHeader> psmsReceiveHeader { get; set; }
        public virtual ICollection<psmsStoreRequisitionHeader> psmsStoreRequisitionHeader { get; set; }
        public virtual ICollection<psmsAdjustmentHeader> psmsAdjustmentHeader { get; set; }
        public virtual ICollection<psmsDelivery> psmsDelivery { get; set; }
        public virtual ICollection<psmsFreightOrder> psmsFreightOrder { get; set; }
        public virtual ICollection<psmsTransportation> psmsTransportation { get; set; }
    }
}
