//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class lupPriceGroup
    {
        public lupPriceGroup()
        {
            this.slmsProformaDetail = new HashSet<slmsProformaDetail>();
            this.slmsSalesDetail = new HashSet<slmsSalesDetail>();
            this.slmsItemPrice = new HashSet<slmsItemPrice>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual ICollection<slmsProformaDetail> slmsProformaDetail { get; set; }
        public virtual ICollection<slmsSalesDetail> slmsSalesDetail { get; set; }
        public virtual ICollection<slmsItemPrice> slmsItemPrice { get; set; }
    }
}
