//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class lupVoucherStatus
    {
        public lupVoucherStatus()
        {
            this.coreVoucherWorkFlow = new HashSet<coreVoucherWorkFlow>();
            this.PRNotification = new HashSet<PRNotification>();
            this.PRProductionOrderHeader = new HashSet<PRProductionOrderHeader>();
            this.PRProductionPlanHeader = new HashSet<PRProductionPlanHeader>();
            this.PRProductionPlanHeader1 = new HashSet<PRProductionPlanHeader>();
            this.psmsAdjustmentDetail = new HashSet<psmsAdjustmentDetail>();
            this.psmsApprover = new HashSet<psmsApprover>();
            this.psmsDeliveryOrderDetail = new HashSet<psmsDeliveryOrderDetail>();
            this.psmsDeliveryOrderHeader = new HashSet<psmsDeliveryOrderHeader>();
            this.psmsDisposalDetail = new HashSet<psmsDisposalDetail>();
            this.psmsDisposalHeader = new HashSet<psmsDisposalHeader>();
            this.psmsIssueDetail = new HashSet<psmsIssueDetail>();
            this.psmsNotification = new HashSet<psmsNotification>();
            this.psmsPurchaseOrderDetail = new HashSet<psmsPurchaseOrderDetail>();
            this.psmsPurchaseOrderHeader = new HashSet<psmsPurchaseOrderHeader>();
            this.psmsPurchaseRequestDetail = new HashSet<psmsPurchaseRequestDetail>();
            this.psmsPurchaseRequestHeader = new HashSet<psmsPurchaseRequestHeader>();
            this.psmsReceiveDetail = new HashSet<psmsReceiveDetail>();
            this.psmsRequestOrderDetail = new HashSet<psmsRequestOrderDetail>();
            this.psmsRequestOrderHeader = new HashSet<psmsRequestOrderHeader>();
            this.psmsReturnDetail = new HashSet<psmsReturnDetail>();
            this.psmsReturnHeader = new HashSet<psmsReturnHeader>();
            this.psmsStoreRequisitionDetail = new HashSet<psmsStoreRequisitionDetail>();
            this.psmsTransferIssueDetail = new HashSet<psmsTransferIssueDetail>();
            this.psmsTransferIssueHeader = new HashSet<psmsTransferIssueHeader>();
            this.psmsTransferReceiveDetail = new HashSet<psmsTransferReceiveDetail>();
            this.psmsTransferReceiveHeader = new HashSet<psmsTransferReceiveHeader>();
            this.slmsProformaHeader = new HashSet<slmsProformaHeader>();
            this.psmsIssueHeader = new HashSet<psmsIssueHeader>();
            this.psmsReceiveHeader = new HashSet<psmsReceiveHeader>();
            this.psmsStoreRequisitionHeader = new HashSet<psmsStoreRequisitionHeader>();
            this.PRProductionPlanJobCardDetail = new HashSet<PRProductionPlanJobCardDetail>();
            this.psmsAdjustmentHeader = new HashSet<psmsAdjustmentHeader>();
            this.psmsDelivery = new HashSet<psmsDelivery>();
            this.psmsFreightOrder = new HashSet<psmsFreightOrder>();
            this.psmsTransportation = new HashSet<psmsTransportation>();
            this.slmsSalesHeader = new HashSet<slmsSalesHeader>();
            this.slmsProformaDetail = new HashSet<slmsProformaDetail>();
            this.slmsSalesDetail = new HashSet<slmsSalesDetail>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual ICollection<coreVoucherWorkFlow> coreVoucherWorkFlow { get; set; }
        public virtual ICollection<PRNotification> PRNotification { get; set; }
        public virtual ICollection<PRProductionOrderHeader> PRProductionOrderHeader { get; set; }
        public virtual ICollection<PRProductionPlanHeader> PRProductionPlanHeader { get; set; }
        public virtual ICollection<PRProductionPlanHeader> PRProductionPlanHeader1 { get; set; }
        public virtual ICollection<psmsAdjustmentDetail> psmsAdjustmentDetail { get; set; }
        public virtual ICollection<psmsApprover> psmsApprover { get; set; }
        public virtual ICollection<psmsDeliveryOrderDetail> psmsDeliveryOrderDetail { get; set; }
        public virtual ICollection<psmsDeliveryOrderHeader> psmsDeliveryOrderHeader { get; set; }
        public virtual ICollection<psmsDisposalDetail> psmsDisposalDetail { get; set; }
        public virtual ICollection<psmsDisposalHeader> psmsDisposalHeader { get; set; }
        public virtual ICollection<psmsIssueDetail> psmsIssueDetail { get; set; }
        public virtual ICollection<psmsNotification> psmsNotification { get; set; }
        public virtual ICollection<psmsPurchaseOrderDetail> psmsPurchaseOrderDetail { get; set; }
        public virtual ICollection<psmsPurchaseOrderHeader> psmsPurchaseOrderHeader { get; set; }
        public virtual ICollection<psmsPurchaseRequestDetail> psmsPurchaseRequestDetail { get; set; }
        public virtual ICollection<psmsPurchaseRequestHeader> psmsPurchaseRequestHeader { get; set; }
        public virtual ICollection<psmsReceiveDetail> psmsReceiveDetail { get; set; }
        public virtual ICollection<psmsRequestOrderDetail> psmsRequestOrderDetail { get; set; }
        public virtual ICollection<psmsRequestOrderHeader> psmsRequestOrderHeader { get; set; }
        public virtual ICollection<psmsReturnDetail> psmsReturnDetail { get; set; }
        public virtual ICollection<psmsReturnHeader> psmsReturnHeader { get; set; }
        public virtual ICollection<psmsStoreRequisitionDetail> psmsStoreRequisitionDetail { get; set; }
        public virtual ICollection<psmsTransferIssueDetail> psmsTransferIssueDetail { get; set; }
        public virtual ICollection<psmsTransferIssueHeader> psmsTransferIssueHeader { get; set; }
        public virtual ICollection<psmsTransferReceiveDetail> psmsTransferReceiveDetail { get; set; }
        public virtual ICollection<psmsTransferReceiveHeader> psmsTransferReceiveHeader { get; set; }
        public virtual ICollection<slmsProformaHeader> slmsProformaHeader { get; set; }
        public virtual ICollection<psmsIssueHeader> psmsIssueHeader { get; set; }
        public virtual ICollection<psmsReceiveHeader> psmsReceiveHeader { get; set; }
        public virtual ICollection<psmsStoreRequisitionHeader> psmsStoreRequisitionHeader { get; set; }
        public virtual ICollection<PRProductionPlanJobCardDetail> PRProductionPlanJobCardDetail { get; set; }
        public virtual ICollection<psmsAdjustmentHeader> psmsAdjustmentHeader { get; set; }
        public virtual ICollection<psmsDelivery> psmsDelivery { get; set; }
        public virtual ICollection<psmsFreightOrder> psmsFreightOrder { get; set; }
        public virtual ICollection<psmsTransportation> psmsTransportation { get; set; }
        public virtual ICollection<slmsSalesHeader> slmsSalesHeader { get; set; }
        public virtual ICollection<slmsProformaDetail> slmsProformaDetail { get; set; }
        public virtual ICollection<slmsSalesDetail> slmsSalesDetail { get; set; }
    }
}
