//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class lupVoucherType
    {
        public lupVoucherType()
        {
            this.coreVoucherWorkFlow = new HashSet<coreVoucherWorkFlow>();
            this.PRNotification = new HashSet<PRNotification>();
            this.psmsApprover = new HashSet<psmsApprover>();
            this.psmsBinCard = new HashSet<psmsBinCard>();
            this.psmsCustodian_ = new HashSet<psmsCustodian_>();
            this.psmsItemLocationTransaction = new HashSet<psmsItemLocationTransaction>();
            this.psmsNotification = new HashSet<psmsNotification>();
            this.psmsVoucherStatusTransaction = new HashSet<psmsVoucherStatusTransaction>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public bool IsFinanceVoucher { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual ICollection<coreVoucherWorkFlow> coreVoucherWorkFlow { get; set; }
        public virtual ICollection<PRNotification> PRNotification { get; set; }
        public virtual ICollection<psmsApprover> psmsApprover { get; set; }
        public virtual ICollection<psmsBinCard> psmsBinCard { get; set; }
        public virtual ICollection<psmsCustodian_> psmsCustodian_ { get; set; }
        public virtual ICollection<psmsItemLocationTransaction> psmsItemLocationTransaction { get; set; }
        public virtual ICollection<psmsNotification> psmsNotification { get; set; }
        public virtual ICollection<psmsVoucherStatusTransaction> psmsVoucherStatusTransaction { get; set; }
    }
}
