//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRBillofMaterialDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid BillofMaterialHeaderId { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> ItemId { get; set; }
        public Nullable<System.Guid> StoreId { get; set; }
        public Nullable<System.Guid> SubAssemblyBillofMaterialHeaderId { get; set; }
        public System.Guid UnitId { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> ScrapQuantity { get; set; }
        public decimal UnitCost { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual lupMeasurementUnit lupMeasurementUnit { get; set; }
        public virtual PRBillofMaterialHeader PRBillofMaterialHeader { get; set; }
        public virtual PRBillofMaterialHeader PRBillofMaterialHeader1 { get; set; }
        public virtual psmsItem psmsItem { get; set; }
        public virtual psmsStore psmsStore { get; set; }
    }
}
