//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRNotification
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public System.DateTime Date { get; set; }
        public string Message { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<System.Guid> VoucherTypeId { get; set; }
        public Nullable<System.Guid> VoucherStatusId { get; set; }
        public bool IsViewed { get; set; }
        public bool IsEmailed { get; set; }
        public bool IsSMSSent { get; set; }
        public string DocumentUrl { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
    
        public virtual coreUser coreUser { get; set; }
        public virtual lupVoucherStatus lupVoucherStatus { get; set; }
        public virtual lupVoucherType lupVoucherType { get; set; }
    }
}
