//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROperation
    {
        public PROperation()
        {
            this.PRProductionPlanJobCardDetail = new HashSet<PRProductionPlanJobCardDetail>();
            this.PRBillofMaterialOperationDetail = new HashSet<PRBillofMaterialOperationDetail>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> WorkStationId { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual PRWorkStation PRWorkStation { get; set; }
        public virtual ICollection<PRProductionPlanJobCardDetail> PRProductionPlanJobCardDetail { get; set; }
        public virtual ICollection<PRBillofMaterialOperationDetail> PRBillofMaterialOperationDetail { get; set; }
    }
}
