//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRProductionPlanDeliveryHeader
    {
        public PRProductionPlanDeliveryHeader()
        {
            this.PRProductionPlanDeliveryDetail = new HashSet<PRProductionPlanDeliveryDetail>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ProductionPlanHeaderId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public decimal Quantity { get; set; }
        public System.Guid StatusId { get; set; }
        public Nullable<System.Guid> AssignedId { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual coreUser coreUser { get; set; }
        public virtual ICollection<PRProductionPlanDeliveryDetail> PRProductionPlanDeliveryDetail { get; set; }
        public virtual PRProductionPlanHeader PRProductionPlanHeader { get; set; }
    }
}
