//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRProductionOrderHeader
    {
        public PRProductionOrderHeader()
        {
            this.PRProductionOrderDetail = new HashSet<PRProductionOrderDetail>();
            this.psmsIssueHeader = new HashSet<psmsIssueHeader>();
            this.psmsStoreRequisitionHeader = new HashSet<psmsStoreRequisitionHeader>();
            this.psmsReturnHeader = new HashSet<psmsReturnHeader>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> SalesOrderId { get; set; }
        public string BarCode { get; set; }
        public string ReferenceNo { get; set; }
        public string VoucherNumber { get; set; }
        public System.Guid FiscalYearId { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.Guid SalesAreaId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.Guid> StoreId { get; set; }
        public System.DateTime PromisedDate { get; set; }
        public System.Guid PreparedById { get; set; }
        public bool IsPosted { get; set; }
        public System.Guid StatusId { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual coreFiscalYear coreFiscalYear { get; set; }
        public virtual coreUser coreUser { get; set; }
        public virtual lupVoucherStatus lupVoucherStatus { get; set; }
        public virtual ICollection<PRProductionOrderDetail> PRProductionOrderDetail { get; set; }
        public virtual psmsStore psmsStore { get; set; }
        public virtual ICollection<psmsIssueHeader> psmsIssueHeader { get; set; }
        public virtual ICollection<psmsStoreRequisitionHeader> psmsStoreRequisitionHeader { get; set; }
        public virtual ICollection<psmsReturnHeader> psmsReturnHeader { get; set; }
        public virtual slmsCustomer slmsCustomer { get; set; }
        public virtual slmsSalesHeader slmsSalesHeader { get; set; }
        public virtual slmsSalesArea slmsSalesArea { get; set; }
    }
}
