//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRProductionCenter
    {
        public System.Guid Id { get; set; }
        public System.Guid ItemCategoryId { get; set; }
        public System.Guid UnitId { get; set; }
    
        public virtual coreUnit coreUnit { get; set; }
        public virtual psmsItemCategory psmsItemCategory { get; set; }
    }
}
