//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRProductionOrderDetail
    {
        public PRProductionOrderDetail()
        {
            this.PRProductionPlanDeliveryDetail = new HashSet<PRProductionPlanDeliveryDetail>();
            this.PRProductionPlanDetail = new HashSet<PRProductionPlanDetail>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ProductionOrderHeaderId { get; set; }
        public Nullable<System.Guid> ItemId { get; set; }
        public System.Guid UnitId { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> SoldQuantity { get; set; }
        public Nullable<decimal> RemainingQuantity { get; set; }
        public decimal UnitCost { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual lupMeasurementUnit lupMeasurementUnit { get; set; }
        public virtual PRProductionOrderHeader PRProductionOrderHeader { get; set; }
        public virtual ICollection<PRProductionPlanDeliveryDetail> PRProductionPlanDeliveryDetail { get; set; }
        public virtual ICollection<PRProductionPlanDetail> PRProductionPlanDetail { get; set; }
        public virtual psmsItem psmsItem { get; set; }
    }
}
