//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRProductionPlanJobCardDetail
    {
        public PRProductionPlanJobCardDetail()
        {
            this.PRProductionPlanJobCardResultDetail = new HashSet<PRProductionPlanJobCardResultDetail>();
            this.PRProductionPlanJobCardTeamDetail = new HashSet<PRProductionPlanJobCardTeamDetail>();
        }
    
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public System.Guid ProductionPlanHeaderId { get; set; }
        public System.Guid OperationId { get; set; }
        public Nullable<System.Guid> AssignedEmployeeId { get; set; }
        public System.Guid WorkStationId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string StartMinute { get; set; }
        public string EndMinute { get; set; }
        public Nullable<decimal> Interval { get; set; }
        public Nullable<decimal> HourRate { get; set; }
        public Nullable<decimal> OperationTime { get; set; }
        public Nullable<System.Guid> StatusId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual coreUser coreUser { get; set; }
        public virtual lupVoucherStatus lupVoucherStatus { get; set; }
        public virtual PROperation PROperation { get; set; }
        public virtual PRProductionPlanHeader PRProductionPlanHeader { get; set; }
        public virtual PRWorkStation PRWorkStation { get; set; }
        public virtual ICollection<PRProductionPlanJobCardResultDetail> PRProductionPlanJobCardResultDetail { get; set; }
        public virtual ICollection<PRProductionPlanJobCardTeamDetail> PRProductionPlanJobCardTeamDetail { get; set; }
    }
}
