//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class psmsPurchaseRequestHeader
    {
        public psmsPurchaseRequestHeader()
        {
            this.psmsPurchaseOrderHeader = new HashSet<psmsPurchaseOrderHeader>();
            this.psmsPurchaseRequestDetail = new HashSet<psmsPurchaseRequestDetail>();
            this.psmsReceiveHeader = new HashSet<psmsReceiveHeader>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid FiscalYearId { get; set; }
        public string VoucherNumber { get; set; }
        public Nullable<System.Guid> PurchaseTypeId { get; set; }
        public System.Guid ConsumerTypeId { get; set; }
        public Nullable<System.Guid> ConsumerStoreId { get; set; }
        public Nullable<System.Guid> ConsumerEmployeeId { get; set; }
        public Nullable<System.Guid> ConsumerUnitId { get; set; }
        public System.Guid RequestTypeId { get; set; }
        public Nullable<System.Guid> RequestOrderHeaderId { get; set; }
        public System.Guid StoreId { get; set; }
        public System.Guid PreparedById { get; set; }
        public System.Guid RequestedById { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public System.DateTime RequiredDate { get; set; }
        public System.Guid StatusId { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual coreFiscalYear coreFiscalYear { get; set; }
        public virtual coreUnit coreUnit { get; set; }
        public virtual coreUser coreUser { get; set; }
        public virtual coreUser coreUser1 { get; set; }
        public virtual coreUser coreUser2 { get; set; }
        public virtual lupConsumerType lupConsumerType { get; set; }
        public virtual lupPurchaseRequestType lupPurchaseRequestType { get; set; }
        public virtual lupVoucherStatus lupVoucherStatus { get; set; }
        public virtual ICollection<psmsPurchaseOrderHeader> psmsPurchaseOrderHeader { get; set; }
        public virtual ICollection<psmsPurchaseRequestDetail> psmsPurchaseRequestDetail { get; set; }
        public virtual psmsRequestOrderHeader psmsRequestOrderHeader { get; set; }
        public virtual psmsStore psmsStore { get; set; }
        public virtual psmsStore psmsStore1 { get; set; }
        public virtual ICollection<psmsReceiveHeader> psmsReceiveHeader { get; set; }
    }
}
