//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class psmsSupplier
    {
        public psmsSupplier()
        {
            this.psmsDocumentNoSetting = new HashSet<psmsDocumentNoSetting>();
            this.psmsPurchaseOrderHeader = new HashSet<psmsPurchaseOrderHeader>();
            this.psmsReturnHeader = new HashSet<psmsReturnHeader>();
            this.psmsReceiveHeader = new HashSet<psmsReceiveHeader>();
            this.psmsSupplierCredit = new HashSet<psmsSupplierCredit>();
            this.psmsSupplierSettlementHeader = new HashSet<psmsSupplierSettlementHeader>();
            this.psmsDelivery = new HashSet<psmsDelivery>();
            this.psmsFreightOrder = new HashSet<psmsFreightOrder>();
            this.psmsTransportation = new HashSet<psmsTransportation>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid SupplierCategoryId { get; set; }
        public Nullable<System.Guid> SubsidiaryAccountId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ContactPerson { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string TIN { get; set; }
        public string VAT { get; set; }
        public string TaxRateIds { get; set; }
        public string TaxRateDescription { get; set; }
        public string PurchaseModality { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual lupSupplierCategory lupSupplierCategory { get; set; }
        public virtual ICollection<psmsDocumentNoSetting> psmsDocumentNoSetting { get; set; }
        public virtual ICollection<psmsPurchaseOrderHeader> psmsPurchaseOrderHeader { get; set; }
        public virtual ICollection<psmsReturnHeader> psmsReturnHeader { get; set; }
        public virtual ICollection<psmsReceiveHeader> psmsReceiveHeader { get; set; }
        public virtual ICollection<psmsSupplierCredit> psmsSupplierCredit { get; set; }
        public virtual ICollection<psmsSupplierSettlementHeader> psmsSupplierSettlementHeader { get; set; }
        public virtual ICollection<psmsDelivery> psmsDelivery { get; set; }
        public virtual ICollection<psmsFreightOrder> psmsFreightOrder { get; set; }
        public virtual ICollection<psmsTransportation> psmsTransportation { get; set; }
    }
}
