//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class psmsBinCard
    {
        public System.Guid Id { get; set; }
        public Nullable<long> IdentityId { get; set; }
        public System.Guid StoreId { get; set; }
        public System.Guid ItemId { get; set; }
        public System.Guid FiscalYearId { get; set; }
        public Nullable<System.Guid> VoucherTypeId { get; set; }
        public System.Guid VoucherId { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<System.Guid> CostTypeId { get; set; }
        public Nullable<System.Guid> ItemCostId { get; set; }
        public System.DateTime Date { get; set; }
        public double CurrentQuantity { get; set; }
        public double ReceivedQuantity { get; set; }
        public double IssuedQuantity { get; set; }
        public decimal AverageCost { get; set; }
        public decimal UnitCost { get; set; }
        public decimal InAmount { get; set; }
        public decimal OutAmount { get; set; }
        public decimal CurrentAmount { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Total { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.Guid> FromStoreId { get; set; }
        public Nullable<System.Guid> FromVoucherId { get; set; }
    
        public virtual coreFiscalYear coreFiscalYear { get; set; }
        public virtual lupVoucherType lupVoucherType { get; set; }
        public virtual psmsItem psmsItem { get; set; }
        public virtual psmsStore psmsStore { get; set; }
    }
}
