//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class psmsPurchaseOrderHeader
    {
        public psmsPurchaseOrderHeader()
        {
            this.psmsPurchaseOrderDetail = new HashSet<psmsPurchaseOrderDetail>();
            this.psmsReceiveHeader = new HashSet<psmsReceiveHeader>();
            this.psmsSupplierSettlementDetail = new HashSet<psmsSupplierSettlementDetail>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid FiscalYearId { get; set; }
        public string VoucherNumber { get; set; }
        public string Version { get; set; }
        public string SupplierReferenceNo { get; set; }
        public System.Guid OrderTypeId { get; set; }
        public Nullable<System.Guid> PurchaseRequestHeaderId { get; set; }
        public System.Guid SupplierId { get; set; }
        public System.Guid StoreId { get; set; }
        public string TaxRateIds { get; set; }
        public System.Guid PreparedById { get; set; }
        public System.Guid OrderedById { get; set; }
        public System.DateTime OrderedDate { get; set; }
        public string TaxRateDescription { get; set; }
        public string TotalSummarry { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public System.Guid StatusId { get; set; }
        public string Remark { get; set; }
        public bool IsPosted { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string SalesType { get; set; }
    
        public virtual coreFiscalYear coreFiscalYear { get; set; }
        public virtual coreUser coreUser { get; set; }
        public virtual coreUser coreUser1 { get; set; }
        public virtual lupPurchaseOrderType lupPurchaseOrderType { get; set; }
        public virtual lupVoucherStatus lupVoucherStatus { get; set; }
        public virtual ICollection<psmsPurchaseOrderDetail> psmsPurchaseOrderDetail { get; set; }
        public virtual psmsPurchaseRequestHeader psmsPurchaseRequestHeader { get; set; }
        public virtual psmsStore psmsStore { get; set; }
        public virtual psmsSupplier psmsSupplier { get; set; }
        public virtual ICollection<psmsReceiveHeader> psmsReceiveHeader { get; set; }
        public virtual ICollection<psmsSupplierSettlementDetail> psmsSupplierSettlementDetail { get; set; }
    }
}
