//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class psmsPurchaseOrderATCDetail
    {
        public psmsPurchaseOrderATCDetail()
        {
            this.psmsFreightOrder = new HashSet<psmsFreightOrder>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid PurchaseOrderDetailId { get; set; }
        public Nullable<double> ATC { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public string InvoiceNo { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> DeliveredQuantity { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool IsDelivered { get; set; }
    
        public virtual ICollection<psmsFreightOrder> psmsFreightOrder { get; set; }
        public virtual psmsPurchaseOrderDetail psmsPurchaseOrderDetail { get; set; }
        public virtual slmsCustomer slmsCustomer { get; set; }
    }
}
