//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class psmsPurchaseOrderDetail
    {
        public psmsPurchaseOrderDetail()
        {
            this.psmsPurchaseOrderATCDetail = new HashSet<psmsPurchaseOrderATCDetail>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid PurchaseOrderHeaderId { get; set; }
        public Nullable<System.Guid> ItemId { get; set; }
        public string Description { get; set; }
        public System.Guid UnitId { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> RemainingQuantity { get; set; }
        public decimal UnitCost { get; set; }
        public decimal Tax { get; set; }
        public System.Guid StatusId { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<double> ATCFrom { get; set; }
        public Nullable<double> ATCTo { get; set; }
        public Nullable<decimal> TruckSize { get; set; }
        public Nullable<decimal> NoofATC { get; set; }
    
        public virtual lupMeasurementUnit lupMeasurementUnit { get; set; }
        public virtual lupVoucherStatus lupVoucherStatus { get; set; }
        public virtual psmsItem psmsItem { get; set; }
        public virtual psmsPurchaseOrderHeader psmsPurchaseOrderHeader { get; set; }
        public virtual ICollection<psmsPurchaseOrderATCDetail> psmsPurchaseOrderATCDetail { get; set; }
    }
}
