//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class psmsReturnHeader
    {
        public psmsReturnHeader()
        {
            this.psmsReturnDetail = new HashSet<psmsReturnDetail>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid FiscalYearId { get; set; }
        public string VoucherNumber { get; set; }
        public System.Guid ConsumerTypeId { get; set; }
        public Nullable<System.Guid> ConsumerStoreId { get; set; }
        public Nullable<System.Guid> ConsumerEmployeeId { get; set; }
        public Nullable<System.Guid> ConsumerUnitId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.Guid> SupplierId { get; set; }
        public Nullable<System.Guid> IssueHeaderId { get; set; }
        public System.Guid ReturnTypeId { get; set; }
        public System.Guid StoreId { get; set; }
        public System.Guid PreparedById { get; set; }
        public System.Guid ReturnedById { get; set; }
        public System.DateTime ReturnedDate { get; set; }
        public System.Guid StatusId { get; set; }
        public string Remark { get; set; }
        public bool IsPosted { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.Guid> ProductionOrderId { get; set; }
        public Nullable<System.Guid> ProductionPlanId { get; set; }
    
        public virtual coreFiscalYear coreFiscalYear { get; set; }
        public virtual coreUnit coreUnit { get; set; }
        public virtual coreUser coreUser { get; set; }
        public virtual coreUser coreUser1 { get; set; }
        public virtual coreUser coreUser2 { get; set; }
        public virtual lupConsumerType lupConsumerType { get; set; }
        public virtual lupReturnType lupReturnType { get; set; }
        public virtual lupVoucherStatus lupVoucherStatus { get; set; }
        public virtual ICollection<psmsReturnDetail> psmsReturnDetail { get; set; }
        public virtual psmsStore psmsStore { get; set; }
        public virtual psmsStore psmsStore1 { get; set; }
        public virtual psmsSupplier psmsSupplier { get; set; }
        public virtual psmsIssueHeader psmsIssueHeader { get; set; }
        public virtual PRProductionOrderHeader PRProductionOrderHeader { get; set; }
        public virtual PRProductionPlanHeader PRProductionPlanHeader { get; set; }
    }
}
