//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class psmsItemLocation
    {
        public psmsItemLocation()
        {
            this.psmsItemLocationTransaction = new HashSet<psmsItemLocationTransaction>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ItemId { get; set; }
        public System.Guid StoreId { get; set; }
        public Nullable<System.Guid> LocationId { get; set; }
        public Nullable<System.Guid> LocationBinId { get; set; }
        public decimal Quantity { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual psmsItem psmsItem { get; set; }
        public virtual psmsStore psmsStore { get; set; }
        public virtual psmsStoreLocation psmsStoreLocation { get; set; }
        public virtual psmsStoreLocationBin psmsStoreLocationBin { get; set; }
        public virtual ICollection<psmsItemLocationTransaction> psmsItemLocationTransaction { get; set; }
    }
}
