//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class psmsStoreLocationBin
    {
        public psmsStoreLocationBin()
        {
            this.psmsItemLocation = new HashSet<psmsItemLocation>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> StoreLocationId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public decimal Size { get; set; }
        public decimal Capacity { get; set; }
        public decimal UtilizedSpace { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual ICollection<psmsItemLocation> psmsItemLocation { get; set; }
        public virtual psmsStoreLocation psmsStoreLocation { get; set; }
    }
}
