//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class psmsDocumentNoSetting
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> StoreId { get; set; }
        public Nullable<System.Guid> SupplierId { get; set; }
        public string DocumentType { get; set; }
        public int NoofDigit { get; set; }
        public string PreFix { get; set; }
        public string SurFix { get; set; }
        public int LastNumber { get; set; }
        public Nullable<int> Year { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual psmsSupplier psmsSupplier { get; set; }
        public virtual psmsStore psmsStore { get; set; }
    }
}
