//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class psmsReceiveDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid ReceiveHeaderId { get; set; }
        public System.Guid ItemId { get; set; }
        public Nullable<System.Guid> UnitId { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> ReceivedQuantity { get; set; }
        public Nullable<decimal> RemainingQuantity { get; set; }
        public Nullable<decimal> DamagedQuantity { get; set; }
        public System.Guid StatusId { get; set; }
        public decimal UnitCost { get; set; }
        public decimal Tax { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ExpireyDate { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.Guid> ProductionDeliveryDetailId { get; set; }
    
        public virtual lupMeasurementUnit lupMeasurementUnit { get; set; }
        public virtual lupVoucherStatus lupVoucherStatus { get; set; }
        public virtual psmsItem psmsItem { get; set; }
        public virtual PRProductionPlanDeliveryDetail PRProductionPlanDeliveryDetail { get; set; }
        public virtual psmsReceiveHeader psmsReceiveHeader { get; set; }
    }
}
