//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class psmsItemLOT
    {
        public psmsItemLOT()
        {
            this.psmsItemLOTTransaction = new HashSet<psmsItemLOTTransaction>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ItemId { get; set; }
        public System.Guid StoreId { get; set; }
        public string Number { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> CommittedQuantity { get; set; }
        public Nullable<System.DateTime> ManufacturedDate { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual psmsItem psmsItem { get; set; }
        public virtual psmsStore psmsStore { get; set; }
        public virtual ICollection<psmsItemLOTTransaction> psmsItemLOTTransaction { get; set; }
    }
}
