//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class psmsVoucherStatusTransaction
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> VoucherTypeId { get; set; }
        public Nullable<System.Guid> VoucherId { get; set; }
        public string VoucherNumber { get; set; }
        public System.Guid StatusId { get; set; }
        public string StatusName { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string Remark { get; set; }
    
        public virtual coreUser coreUser { get; set; }
        public virtual lupVoucherType lupVoucherType { get; set; }
    }
}
