//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class psmsItemSerial
    {
        public psmsItemSerial()
        {
            this.psmsCustodian_ = new HashSet<psmsCustodian_>();
            this.psmsItemSerialTransaction = new HashSet<psmsItemSerialTransaction>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ItemId { get; set; }
        public System.Guid StoreId { get; set; }
        public string Number { get; set; }
        public string PlateNo { get; set; }
        public bool IsAvailable { get; set; }
        public string GRNNumber { get; set; }
        public Nullable<System.DateTime> GRNDate { get; set; }
        public string Description { get; set; }
        public string SN { get; set; }
        public Nullable<decimal> PurchaseCost { get; set; }
        public bool IsDisposed { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual ICollection<psmsCustodian_> psmsCustodian_ { get; set; }
        public virtual psmsItem psmsItem { get; set; }
        public virtual psmsStore psmsStore { get; set; }
        public virtual ICollection<psmsItemSerialTransaction> psmsItemSerialTransaction { get; set; }
    }
}
