//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class psmsInventoryRecord
    {
        public System.Guid Id { get; set; }
        public System.Guid StoreId { get; set; }
        public System.Guid ItemId { get; set; }
        public System.Guid FiscalYearId { get; set; }
        public double BeginingQuantity { get; set; }
        public double RunningQuantity { get; set; }
        public double AvailableQuantity { get; set; }
        public decimal UnitCost { get; set; }
        public Nullable<double> CommittedQuantity { get; set; }
        public double PhysicalQuantity { get; set; }
        public double ClosingQuantity { get; set; }
        public Nullable<double> DamagedQuantity { get; set; }
        public Nullable<double> OrderedQuantity { get; set; }
        public Nullable<double> ExpiredQuantity { get; set; }
        public string Remarks { get; set; }
        public Nullable<double> ReorderLevel { get; set; }
        public Nullable<double> MaximumLevel { get; set; }
        public Nullable<double> MinimumLevel { get; set; }
        public Nullable<double> SafetyStock { get; set; }
        public Nullable<double> LeadTime { get; set; }
        public Nullable<double> OrderingCost { get; set; }
        public Nullable<double> CarryingCost { get; set; }
        public Nullable<double> ShortageQuantity { get; set; }
        public Nullable<double> OverageQuantity { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public bool IsClosed { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> ReorderdDate { get; set; }
        public Nullable<decimal> PendingReorderQuantity { get; set; }
        public Nullable<System.DateTime> ExpireyDate { get; set; }
    
        public virtual coreFiscalYear coreFiscalYear { get; set; }
        public virtual psmsItem psmsItem { get; set; }
        public virtual psmsStore psmsStore { get; set; }
    }
}
