//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class psmsItemCategory
    {
        public psmsItemCategory()
        {
            this.PRBillofMaterialHeader = new HashSet<PRBillofMaterialHeader>();
            this.PRProductionCenter = new HashSet<PRProductionCenter>();
            this.psmsItem = new HashSet<psmsItem>();
            this.psmsItemCategory1 = new HashSet<psmsItemCategory>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public System.Guid TypeId { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual lupItemCategoryType lupItemCategoryType { get; set; }
        public virtual ICollection<PRBillofMaterialHeader> PRBillofMaterialHeader { get; set; }
        public virtual ICollection<PRProductionCenter> PRProductionCenter { get; set; }
        public virtual ICollection<psmsItem> psmsItem { get; set; }
        public virtual ICollection<psmsItemCategory> psmsItemCategory1 { get; set; }
        public virtual psmsItemCategory psmsItemCategory2 { get; set; }
    }
}
