//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class slmsSalesArea
    {
        public slmsSalesArea()
        {
            this.PRProductionOrderHeader = new HashSet<PRProductionOrderHeader>();
            this.slmsProformaHeader = new HashSet<slmsProformaHeader>();
            this.slmsSalesHeader = new HashSet<slmsSalesHeader>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> StoreId { get; set; }
        public Nullable<System.Guid> PriceCategoryId { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool IsSalesOrderCommited { get; set; }
    
        public virtual ICollection<PRProductionOrderHeader> PRProductionOrderHeader { get; set; }
        public virtual psmsStore psmsStore { get; set; }
        public virtual ICollection<slmsProformaHeader> slmsProformaHeader { get; set; }
        public virtual ICollection<slmsSalesHeader> slmsSalesHeader { get; set; }
        public virtual slmsPriceCategory slmsPriceCategory { get; set; }
    }
}
