//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class slmsItemPrice
    {
        public System.Guid Id { get; set; }
        public System.Guid PriceCategoryId { get; set; }
        public System.Guid ItemId { get; set; }
        public System.Guid UnitId { get; set; }
        public System.Guid PriceGroupId { get; set; }
        public decimal UnitPrice { get; set; }
        public bool IsTaxable { get; set; }
        public Nullable<decimal> WithHoldingTax { get; set; }
        public bool IsActive { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual lupMeasurementUnit lupMeasurementUnit { get; set; }
        public virtual lupPriceGroup lupPriceGroup { get; set; }
        public virtual psmsItem psmsItem { get; set; }
        public virtual slmsPriceCategory slmsPriceCategory { get; set; }
    }
}
