//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class slmsCustomerCategory
    {
        public slmsCustomerCategory()
        {
            this.slmsCustomerCategory1 = new HashSet<slmsCustomerCategory>();
            this.slmsCustomer = new HashSet<slmsCustomer>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ICollection<slmsCustomerCategory> slmsCustomerCategory1 { get; set; }
        public virtual slmsCustomerCategory slmsCustomerCategory2 { get; set; }
        public virtual ICollection<slmsCustomer> slmsCustomer { get; set; }
    }
}
