//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberErp.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class slmsProformaHeader
    {
        public slmsProformaHeader()
        {
            this.slmsSalesHeader = new HashSet<slmsSalesHeader>();
            this.slmsProformaDetail = new HashSet<slmsProformaDetail>();
        }
    
        public System.Guid Id { get; set; }
        public string VoucherNumber { get; set; }
        public string ReferenceNo { get; set; }
        public System.Guid FiscalYearId { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.Guid SalesAreaId { get; set; }
        public string PaymentTerm { get; set; }
        public string DeliveryCondition { get; set; }
        public Nullable<System.Guid> PriceCategoryId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> ValidityUntilDate { get; set; }
        public bool ApplyWithHolding { get; set; }
        public decimal TaxableAmount { get; set; }
        public decimal Tax { get; set; }
        public Nullable<decimal> WithHolding { get; set; }
        public decimal NetPay { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public System.Guid PreparedById { get; set; }
        public System.Guid SalesPersonId { get; set; }
        public System.Guid StatusId { get; set; }
        public string BankInformation { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] LastUpdated { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual coreFiscalYear coreFiscalYear { get; set; }
        public virtual coreUser coreUser { get; set; }
        public virtual coreUser coreUser1 { get; set; }
        public virtual lupVoucherStatus lupVoucherStatus { get; set; }
        public virtual slmsPriceCategory slmsPriceCategory { get; set; }
        public virtual slmsCustomer slmsCustomer { get; set; }
        public virtual ICollection<slmsSalesHeader> slmsSalesHeader { get; set; }
        public virtual slmsSalesArea slmsSalesArea { get; set; }
        public virtual ICollection<slmsProformaDetail> slmsProformaDetail { get; set; }
    }
}
